### PR TITLE
Refactoring AlexNisnevich/Portfolio to use TypeScript, while maintaining current functionality

### PR DESCRIPTION
**Pull request by blast-hardcheese**
I'd love to use this Portfolio for my own projects, but I feel this could be made into a much more broad framework that other people could use as well. Breaking the core apart seems like it would be beneficial for everyone, I'll start on that next.

### CODE REVIEW

**Comment by blast-hardcheese** [comment]
I figured I should open a pull request before anything major changes

**Comment by AlexNisnevich** [comment]
I agree wholeheartedly with the idea of making Portfolio usable by as many people as possible, but I'm not sure if switching to TypeScript is the way to go, since much fewer people use TypeScript than JavaScript.

**Comment by blast-hardcheese** [comment]
That's one of the two reasons why I also committed the generated javascript (the other being this way, it's still a static site that can be hosted via a static site hoster).

**Comment by AlexNisnevich** [comment]
Even so, this would force future contributors to work in TypeScript rather
than JavaScript. I'm not sure that the benefits of TypeScript are worth it,
especially for a project this small.

**Comment by blast-hardcheese** [comment]
For me, the advantage of TypeScript is huge on any project I didn't write myself, as it fully documents all internal assumptions, and provides a baseline for extension. I definitely agree with you that this project is small enough that TypeScript isn't required, but it's still a huge help (at least for me).

I've also written way more JavaScript than TypeScript, so I'm looking to expand my experience as well.

If you'd rather continue without TypeScript, I'll continue in my own fork, hopefully with no hard feelings. I really don't want to push you in a direction you don't want to go, and I definitely agree with the points you've made.

**Comment by blast-hardcheese** [comment]
Sounds good!

**Comment by blast-hardcheese** [comment]
Found a dangling `var src =` from an earlier refactor.

**Pull request closed without merging**
